spring:
  application:
    name: forum-service
  datasource:
    url: jdbc:postgresql://cohort5860-eddfish.c.aivencloud.com:22423/defaultdb
    username: avnadmin
    password: ${AIVEN_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: ${MONGO_URI}